apiVersion: v1
kind: Service
metadata:
  name: v2ray-paas
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "v2ray-paas"
    port: 80
  selector:
    app: v2ray-okteto
